apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: py
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: py
    spec:
      containers:
        - image: sudarshantn/py3
          name: py
          command: ["tail", "-f" ,"/dev/null"]
          ports:
            - containerPort: 80
        - image: mongo:4.0.0
          name: mongo4
          ports:
            - containerPort: 27017
