version: '3'
services:
  python:
    image: py3
    container_name: python3
    command: tail -F sleep infinity
    volumes:
      - sudvol:/data/tnsvol/
    networks:
      - sudnet
    ports: 
      - "8081:8081"
  mongo:
    image: mongo:4.0.0
    container_name: mongo4
    volumes:
      - sudvol:/data/tnsvol/
    networks:
      - sudnet
    ports: 
      - "27017:27017"
volumes:
  sudvol:
    external: true
networks:
  sudnet:
    external: true
