version: '3'
services:
  python:
    image: python:3.7
    volumes:
      - sudvol:/data/tnsvol/
    networks:
      - sudnet
    ports: -8081:8081 
  mongo:
    image: mongo:4.0.0
    volumes:
      - sudvol:/data/tnsvol/
    networks:
      - sudnet
    ports: 
      - "8082:8082"
volumes:
  sudvol:
    external: true
networks:
  sudnet:
    external: true
